# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
    config.vm.box = "debian/bullseye64"
  
     config.vm.network "private_network", ip: "192.168.54.2"
    # config.vm.network "public_network"
    # config.vm.synced_folder "../data", "/vagrant_data"
    # config.vm.synced_folder ".", "/vagrant", disabled: true
     config.vm.provider "virtualbox" do |vb|
    #   vb.gui = true
    #   vb.memory = "1024"
     end
     
     config.vm.provision "shell", inline: <<-SHELL
       apt-get update
     SHELL
  end
  