pipeline{
    agent {
        label 'builtinnode'
    }
    stages{
        stage('Build Application'){
            steps{
                sh 'mvn -f Jenkins/java-tomcat-sample/pom.xml clean package'
            }
            post{
                success{
                    echo "Archiving the WAR file......"
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage ('Create Tomcat Img'){
            steps{
                original_pwd = $(pwd -P)
                cd /opt/docker/app
                sh 'sudo docker build -t localtomcatimg:$BUILD_NUMBER .'
                cd $original_pwd
            }
        }
        stage('Staging Deployment'){
            steps{
                build job: 'tomcatdeploy'
            }
        }
    }
}