# -*- mode: ruby -*-
# vi: set ft=ruby :
unless Vagrant.has_plugin?("vagrant-disksize")
   raise 'vagrant-disksize not installed'
end
Vagrant.configure("2") do |config|
   config.vm.box = "generic/centos8"
   config.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.memory = "1024"
      vb.cpus = 2
   end
   config.disksize.size = '150GB'
   config.vm.provision "shell", path:"resizeDisk.sh", keep_color: "true" #calling resizeDisk.sh instead of using inline commands
      #resize2fs /dev/sda1     #to resize the filesystem based on extended disksize,
      #only use when shell provisioning enabled
      #works on debian/bullseye64
  
end
  