Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"
  
    config.vm.define "web" do |web|
        web.vm.box = "debian/bullseye64"
        web.vm.network "private_network", ip: "192.168.54.2"
        web.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
        web.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install apache2 unzip -y
            systemctl start apache2
            systemctl enable apache2
            cd /tmp/
            wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip
            unzip -o 2135_mini_finance.zip
            cp -r 2135_mini_finance/* /var/www/html
            systemctl restart apache2
       SHELL
    end
  
    config.vm.define "db" do |db|
      db.vm.box = "debian/bullseye64"
    end
  end