# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.network "private_network", ip: "192.168.54.2"
  config.vm.synced_folder "../test", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end
  config.disksize.size = '84GB'
  #config.vm.provision "shell", inline: <<-SHELL
    #apt-get update
    #apt-get install -y apache2
  #SHELL
end
