# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.network "private_network", ip: "192.168.54.2"     #set the private IP here
    #config.vm.network "public_network"
    config.vm.synced_folder "../staticpage", "/opt/docker"
    config.vm.provider "virtualbox" do |vb|
        #vb.gui = true
        #vb.memory = "1024"
     end 
    config.vm.provision "shell", inline: <<-SHELL
        for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done
        sudo apt-get update
        sudo apt-get install ca-certificates curl gnupg wget zip unzip -y
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
        echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
        cd /opt/docker
        wget https://www.tooplate.com/zip-templates/2136_kool_form_pack.zip            #or you can add the download link of other web templates
        #make sure the web templates are downloaded in zip file or change the extraction process below
        unzip 2136_kool_form_pack.zip
        cd 2136_kool_form_pack
        tar -czvf formpack.tar.gz *
        cd ..
        mv 2136_kool_form_pack/formpack.tar.gz .
        rm -rf 2136_kool_form_pack 2136_kool_form_pack.zip
        docker build -t local-img/formpack:1 .
        docker run -it -d --name formpack -p 8080:80 local-img/formpack:1
        usermod -aG docker vagrant
    SHELL
end
  