pipeline {
    agent any
    stages {
        stage('UnitTest') {
            steps {
                echo "this is a test message for implementing pipeline as a code"
            }
        }
        stage ('Build') {
            steps {
                echo "test message for building the code"
            }
        }
        stage ('DeployStaging') {
            steps {
                echo "test message for deploying to staging"
            }
        }
        stage ('DeployPord') {
            steps {
                echo "Test message for deploying to production"
            }
        }
    }
}