pipeline {
    agent {
        label 'builtinnode'
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f Jenkins/java-tomcat-sample/pom.xml clean package'
            }
            post {
                echo "Archiving the artifacts: "
                archiveArtifacts artifacts: '**/*.war'
            }
        }
        stage ('Build') {
            steps {
                echo "test message for building the code"
            }
        }
        stage ('DeployStaging') {
            steps {
                echo "test message for deploying to staging"
            }
        }
        stage ('DeployPord') {
            steps {
                echo "Test message for deploying to production"
            }
        }
    }
}