pipeline {
    agent {
        label 'builtinnode'
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f Jenkins/java-tomcat-sample/pom.xml clean package'
            }
            post {
                echo "Archiving the artifacts: "
                archiveArtifacts artifacts: '**/*.war'
            }
        }
    }
}